// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenWithGitKraken
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenWithGitKraken.d81d0fd2-99f5-4b73-8380-429ab6c8babd";
        public const string Name = "Open With GitKraken";
        public const string Description = @"Opens the associated git repo of a project or solution with GitKraken.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Steven Roeland";
        public const string Tags = "Solution Explorer, gitkraken, git";
    }
}
